// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plugins.DataStore.SQL;

#nullable disable

namespace Plugins.DataStore.SQL.Migrations
{
    [DbContext(typeof(MarketContext))]
    [Migration("20260512101057_FlowerShopData")]
    partial class FlowerShopData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreBusiness.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Fresh cut flowers for any occasion",
                            Name = "Cut Flowers"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Beautiful indoor and outdoor potted plants",
                            Name = "Potted Plants"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Pre-arranged floral bouquets crafted by our florists",
                            Name = "Bouquets"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Pots, fertilizers, and gardening tools",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("CoreBusiness.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Name = "Red Rose",
                            Price = 2.9900000000000002,
                            Quantity = 150
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Name = "White Tulip",
                            Price = 1.5,
                            Quantity = 200
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Name = "Sunflower",
                            Price = 3.5,
                            Quantity = 80
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Name = "Elegant Orchid",
                            Price = 24.989999999999998,
                            Quantity = 40
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Name = "Monstera Deliciosa",
                            Price = 35.0,
                            Quantity = 30
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Name = "Snake Plant",
                            Price = 18.5,
                            Quantity = 50
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Name = "Birthday Joy Bouquet",
                            Price = 45.0,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Name = "Premium Wedding Roses",
                            Price = 89.989999999999995,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            Name = "Ceramic Pot (Medium)",
                            Price = 12.99,
                            Quantity = 100
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4,
                            Name = "Liquid Flower Fertilizer",
                            Price = 5.9900000000000002,
                            Quantity = 80
                        });
                });

            modelBuilder.Entity("CoreBusiness.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("BeforeQty")
                        .HasColumnType("int");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CoreBusiness.Product", b =>
                {
                    b.HasOne("CoreBusiness.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoreBusiness.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
